### ISSUE TITLE
How to invoke it in config?

### ISSUE THREAD

**Issue by doits** [sheharyarn/capistrano-rake#1]
How to invoke this for e.g. with an `after`?

```
namespace :deploy do
    after :publishing, 'invoke:rake TASK=some:task'
end
```

... does not work. How to do it correctly?

**Comment by sheharyarn** [comment]
This is not the intended use of `capistrano-rake`; it's meant to remotely execute rake operations on servers. If you want to execute rake tasks within capistrano recipes, use the `execute :rake` method. For example:

``` ruby
namespace :deploy do
    after :publishing, :rake_task_name do
        within release_path do
            execute :rake, "my_rake:task"
        end
    end
end
```

Depending on your configuration and rake task, you might have to use `with rails_env`. See the [capistrano guide on before/after hooks](http://capistranorb.com/documentation/getting-started/before-after/) or check out my [paperclip capistrano recipe](https://gist.github.com/sheharyarn/70fa04dd3647163e89b0) to see it in action.
