### ISSUE TITLE
Feature request: ROLES option

### ISSUE THREAD

**Issue by kikito** [sheharyarn/capistrano-rake#3]
Thanks a lot for creating this. Here's one possible improvement that might be useful: limit the execution of the rake task to certain roles. Like so:

```
cap production invoke:rake TASK=queues:relaunch ROLES=cron,background
```

This should execute the tasks only in the server where the roles "cron" and/or "background" are active. For example if the servers are configured like this in `deploy/production.rb`:

```
server 'server1', user: 'deploy', roles: %w(web app db importer cron background)
server 'server2', user: 'deploy', roles: %w(web app db importer cron)
server 'server3', user: 'deploy', roles: %w(web app db importer)
```

Then the invocation mentioned above would execute `rake queues:relaunch` on server1 and server2, but not on server 3.

**Comment by sheharyarn** [comment]
Hi @kikito. I'm not planning on adding any more features to this gem, but if you really feel that it's an important feature to have, PRs are always welcome.

**Comment by swordfish444** [comment]
@kikito @sheharyarn roles are already applied by default in capistrano. 

Your command is failing because your placement of ROLES is incorrect. To fix, simply do this:

```rake
cap ROLES=cron,background production invoke:rake TASK=queues:relaunch
```

Cheers 🎉
