### ISSUE TITLE
Logging using puts not working

### ISSUE THREAD

**Issue by PawelDedio** [sheharyarn/capistrano-rake#6]
Hi, I use a lot of puts in my task but nothing is logged into terminal while invoking this on server, when I run this task on my local machine everything is correct.

Task declaration:
```
namespace :db do
  task backup: :environment do
    puts "Starting database backup " 
```

This is how I run this task:
`cap staging invoke:rake TASK=db:backup`

**Comment by sheharyarn** [comment]
Hmmm, that should not be happening. Were you able to reproduce the issue in a minimal capistrano set up? It's possible that the console output might be affected by different configurations for your `staging` environment.

I assume that the task completes successfully and works as expected even though there is no output, right?

**Comment by PawelDedio** [comment]
I have nothing special in my staging configuration, only server configuration and task for generating doc, but this task is run only after full deploy.

```
set :rails_env, 'production'

after :deploy, 'deploy:generate_doc'

namespace :deploy do
  desc 'generate doc'
  task :generate_doc do
    on roles(:app) do
      execute "apidoc -i #{current_path}/app -o #{current_path}/public/apidoc"
    end
  end
end
```

> I assume that the task completes successfully and works as expected even though there is no output, right?

Yes, task work correctly but it prints no output.

**Comment by PawelDedio** [comment]
Ok I found what was the cause of this. In my task I called `sh` few times, I divided this task to few smaller (only one `sh`call per task) and now everything works correctly.
